name: Jest

on:
  pull_request:
  merge_group:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  file-diff:
    runs-on: ubuntu-22.04
    name: File Diff
    steps:
      - name: Checkout GithubActions repo
        uses: actions/checkout@v4
        with:
          repository: elementor/elementor-cloud-github-actions
          token: ${{ secrets.DEVOPS_TOKEN }}
